### PR TITLE
Replace blocking serial port methods with asynchronous versions.

### PR DESCRIPTION
**Pull request by yurko7**
With non-blocking requests it's much easier to use this library in desktop (e.g. WinForm and WPF) projects.
Asynchronous methods allows users of ArduinoDriver to take full advantages of async/await methods with cancellation and automatic capturing of synchronization context.
Now users of this library can create long running PC-to-Arduino communication workflows without freezing UI.
Also now it's easier to concurrently communicate with a couple of Arduino boards using Task.WhenAll, Task.WhenAny methods.

### CODE REVIEW

**Comment by christophediericx** [comment]
Hi Yurko7,

Thank you for your interest in this library, and for providing a PR. 

Could you please elaborate on what advantages making these methods asynchronous brings (and in particular, for this library)?

Thanks,

Christophe

**Comment by yurko7** [comment]
Hi Christophe,
I have updated comment of the PR.
Thank you!

**Comment by christophediericx** [comment]
Thanks for providing some more context. I'll test the changes with a couple of devices this weekend. If no issues pop up, I'll merge the pull request.

**Comment by christophediericx** [comment]
I found some time today to review the Pull Request. While it is solidly implemented, I have decided to still reject it. The reason is that I don't see a very compelling reason to make the entire library implementation asynchronous:

* Serial port communication (in the SerialPortStream dependency implementation) is in itself asynchronous by nature, and with the strict read and write timeouts (in the ArduinoDriver library code), I don't think there is much potential for the code to be "blocking" the UI and / or main thread. All request / response communication should be returning in milliseconds.
* The hinted benefits of parallelization of workloads (e.g. driving multiple Arduinos at the same time) can easily be achieved with the builtin C# task support (this does not strictly require all method signatures in this library to be async).

Overall, the proposed changes would force (some) complexity upon consumers without any tangible rewards (imho).

Thanks for your interest, and for taking the time for committing the PR though!

**Pull request closed without merging**
